SPacketDescription = {
[SID_SERVERLIST] = {
	uint32{label="Server version", },
	stringz{label="[] Server list", },
},
[SID_NEWS_INFO] = {
	uint8{label="Number of entries", },
	uint32{label="Last logon timestamp", },
	uint32{label="Oldest news timestamp", },
	uint32{label="Newest news timestamp", },
	uint32{label="Timestamp", },
	stringz{label="News", },
},
[SID_OPTIONALWORK] = {
	stringz{label="MPQ Filename", },
},
[BNLS_CONFIRMLOGON] = {
	uint32{label="Success", desc=Descs.YesNo},
},
[SID_AUTH_CHECK] = {
	uint32{label="Result", },
	stringz{label="Additional Information", },
},
[MCP_JOINGAME] = {
	uint16{label="Request ID", },
	uint16{label="Game token", },
	uint16{label="Unknown", },
	uint32{label="IP of D2GS Server", },
	uint32{label="Game hash", },
	uint32{label="Result", },
},
[SID_READUSERDATA] = {
	uint32{label="Number of accounts", },
	uint32{label="Number of keys", },
	uint32{label="Request ID", },
	stringz{label="[] Requested Key Values", },
},
[BNLS_CHANGECHALLENGE] = {
	uint32{label="Data for SID_AUTH_ACCOUNTCHANGE", num=8},
},
[SID_CLANMEMBERSTATUSCHANGE] = {
	stringz{label="Username", },
	uint8{label="Rank", },
	uint8{label="Status", },
	stringz{label="Location", },
},
[SID_FRIENDSPOSITION] = {
	uint8{label="Old Position", },
	uint8{label="New Position", },
},
[SID_FRIENDSADD] = {
	stringz{label="Account", },
	uint8{label="Friend Type", },
	uint8{label="Friend Status", },
	uint32{label="ProductID", },
	stringz{label="Location", },
},
[SID_GETICONDATA] = {
	wintime{label="Filetime", },
	stringz{label="Filename", },
},
[BNLS_CDKEY] = {
	uint32{label="Result", desc=Descs.YesNo},
	uint32{label="Client Token", },
	uint32{label="CD key data for SID_AUTH_CHECK", num=9},
},
[PACKET_CYCLE] = {
	stringz{label="Channel", },
},
[BNLS_VERSIONCHECKEX2] = {
	uint32{label="Success*", desc=Descs.YesNo},
	uint32{label="Version.", },
	uint32{label="Checksum.", },
	stringz{label="Version check stat string.", },
	uint32{label="Cookie.", },
	uint32{label="The latest version code for this product.", },
},
[SID_STARTVERSIONING] = {
	wintime{label="MPQ Filetime", },
	stringz{label="MPQ Filename", },
	stringz{label="ValueString", },
},
[BNLS_REQUESTVERSIONBYTE] = {
	uint32{label="Productif Product is nonzero:", },
	uint32{label="Version byte", },
},
[SID_AUTH_ACCOUNTCREATE] = {
	uint32{label="Status", },
},
[PACKET_MESSAGE] = {
	stringz{label="User", },
	stringz{label="Command", },
},
[D2GS_TRADEACTION] = {
	uint8{label="Request Type", },
},
[SID_AUTH_INFO] = {
	uint32{label="Logon Type", },
	uint32{label="Server Token", },
	uint32{label="UDPValue *", },
	wintime{label="MPQ filetime", },
	stringz{label="IX86ver filename", },
	stringz{label="ValueString", },
	bytes{label="128-byte Server signature", },
},
[D2GS_WORLDOBJECT] = {
	uint8{label="Object Type - Any information appreciated", },
	uint32{label="Object ID", },
	uint16{label="Object unique code", },
	uint16{label="X Coordinate", },
	uint16{label="Y Coordinate", },
	uint8{label="State *", },
	uint8{label="Interaction Condition", },
},
[SID_STARTADVEX] = {
	uint32{label="Status", },
},
[SID_CLANINFO] = {
	uint8{label="Unknown", },
	uint32{label="Clan tag", },
	uint8{label="Rank", },
},
[SID_FRIENDSLIST] = {
	uint8{label="Number of Entries", },
	stringz{label="Account", },
	uint8{label="Status", },
	uint8{label="Location", },
	uint32{label="ProductID", },
	stringz{label="Location name", },
},
[SID_CLANCREATIONINVITATION] = {
	uint32{label="Cookie", },
	uint32{label="Clan Tag", },
	stringz{label="Clan Name", },
	stringz{label="Inviter's username", },
	uint8{label="Number of users being invited", },
	stringz{label="[] List of users being invited", },
},
[SID_CLANMEMBERINFORMATION] = {
	uint32{label="Cookie", },
	uint8{label="Status code", },
	stringz{label="Clan name", },
	uint8{label="User's rank", },
	wintime{label="Date joined", },
},
[SID_LOGONCHALLENGE] = {
	uint32{label="Server Token", },
},
[MCP_GAMEINFO] = {
	uint16{label="Request ID", },
	uint32{label="Status *", },
	uint32{label="Game Uptime", },
	uint16{label="Unknown", },
	uint8{label="Maximum players allowed", },
	uint8{label="Number of characters in the game", },
	uint8{label="[16] Classes of ingame characters **", },
	uint8{label="[16] Levels of ingame characters **", },
	uint8{label="Unused", },
	stringz{label="[16] Character names **", },
},
[SID_PING] = {
	uint32{label="Ping Value", },
},
[PKT_SERVERPING] = {
	uint32{label="UDP Code", },
},
[BNLS_SERVERLOGONPROOF] = {
	uint32{label="Slot index.", },
	uint32{label="Success.", desc=Descs.YesNo},
	uint32{label="Data server's", num=5},
},
[SID_STARTADVEX3] = {
	uint32{label="Status", },
},
[SID_REQUIREDWORK] = {
	stringz{label="ExtraWork MPQ FileName", },
},
[BNLS_CREATEACCOUNT] = {
	uint32{label="Data for Data for SID_AUTH_ACCOUNTCREATE", num=16},
},
[SID_CDKEY2] = {
	uint32{label="Result", },
	stringz{label="Key owner", },
},
[SID_ENTERCHAT] = {
	stringz{label="Unique name", },
	stringz{label="Statstring", },
	stringz{label="Account name", },
},
[SID_CDKEY] = {
	uint32{label="Result", },
	stringz{label="Key owner", },
},
[MCP_CHARLIST2] = {
	uint16{label="Number of characters requested", },
	uint32{label="Number of characters that exist on this account", },
	uint16{label="Number of characters returned", },
	uint32{label="Expiration Date", },
	stringz{label="Character name", },
	stringz{label="Character statstring", },
},
[SID_GETFILETIME] = {
	uint32{label="Request ID", },
	uint32{label="Unknown", },
	wintime{label="Last update time", },
	stringz{label="Filename", },
},
[BNLS_AUTHORIZEPROOF] = {
	uint32{label="Status code.", },
},
[PACKET_CHATDROPOPTIONS] = {
	uint8{label="SubcommandFor subcommand 0:", },
	uint8{label="Setting for broadcast", },
	uint8{label="Setting for database", },
	uint8{label="Setting for whispers", },
	uint8{label="Refuse all", },
},
[PACKET_USERINFO] = {
	uint32{label="Bot number", },
	stringz{label="Bot name", },
	stringz{label="Bot channel", },
	uint32{label="Bot server", },
	stringz{label="Unique account name", },
	stringz{label="Current database", },
},
[BNLS_UPGRADEPROOF] = {
	uint32{label="Data for SID_AUTH_ACCOUNTUPGRADEPROOF", num=22},
},
[BNLS_CHANGEPROOF] = {
	uint32{label="Data for SID_AUTH_ACCOUNTCHANGEPROOF", num=21},
},
[PACKET_LOGON] = {
	uint32{label="Result", },
},
[PACKET_BOTNETCHAT] = {
	uint32{label="Command", },
	uint32{label="Action", },
	uint32{label="ID of source bot", },
	stringz{label="Message", },
},
[BNLS_CHOOSENLSREVISION] = {
	uint32{label="Success code.", desc=Descs.YesNo},
},
[SID_AUTH_ACCOUNTLOGON] = {
	uint32{label="Status", },
	uint8{label="[32] Salt", },
	uint8{label="[32] Server Key", },
},
[SID_CLANINVITATION] = {
	uint32{label="Cookie", },
	uint8{label="Result", },
},
[BNLS_VERSIONCHECK] = {
	uint32{label="Success If Success is TRUE:", desc=Descs.YesNo},
	uint32{label="Version.", },
	uint32{label="Checksum.", },
	stringz{label="Version check stat string.", },
},
[SID_CLANMEMBERLIST] = {
	uint32{label="Cookie", },
	uint8{label="Number of Members", },
	stringz{label="Username", },
	uint8{label="Rank", },
	uint8{label="Online Status", },
	stringz{label="Location", },
},
[SID_AUTH_ACCOUNTUPGRADEPROOF] = {
	uint32{label="Status", },
	uint32{label="[5] Password proof", },
},
[SID_CHANGEPASSWORD] = {
	uint32{label="Password change succeeded", desc=Descs.YesNo},
},
[D2GS_SETBYTEATTR] = {
	uint8{label="Attribute", },
	uint8{label="Amount", },
},
[D2GS_SETWORDATTR] = {
	uint8{label="Attribute", },
	uint16{label="Amount", },
},
[SID_SETEMAIL] = {
},
[SID_CREATEACCOUNT] = {
	uint32{label="Result", },
},
[PACKET_USERLOGGINGOFF] = {
	uint32{label="Bot id", },
},
[D2GS_CHARTOOBJ] = {
	uint8{label="Unknown", },
	uint32{label="Player ID", },
	uint8{label="Movement Type", },
	uint8{label="Destination Type", },
	uint32{label="Object ID", },
	uint16{label="X Coordinate", },
	uint16{label="Y Coordinate", },
},
[SID_CLANINVITATIONRESPONSE] = {
	uint32{label="Cookie", },
	uint32{label="Clan tag", },
	stringz{label="Clan name", },
	stringz{label="Inviter", },
},
[MCP_CHARLIST] = {
	uint16{label="Number of characters requested", },
	uint32{label="Number of characters that exist on this account", },
	uint16{label="Number of characters returned", },
	stringz{label="Character name", },
	stringz{label="Character statstring", },
},
[SID_LOGONREALMEX] = {
	uint32{label="MCP Cookie", },
	uint32{label="MCP Status", },
	uint32{label="[2] MCP Chunk 1", },
	uint32{label="IP", },
	uint32{label="Port", },
	uint32{label="[12] MCP Chunk 2", },
	stringz{label="Battle.net unique name", },
},
[BNLS_VERIFYSERVER] = {
	uint32{label="Success.", desc=Descs.YesNo},
},
[SID_GAMEPLAYERSEARCH] = {
	uint8{label="Number of players", },
	stringz{label="[] Player names", },
},
[SID_FLOODDETECTED] = {
},
[PACKET_DATABASE] = {
	uint32{label="command", },
	stringz{label="usermask", },
	stringz{label="flags", },
	stringz{label="usermask", },
},
[D2GS_STARTLOGON] = {
},
[MCP_CHARCREATE] = {
	uint32{label="Result", },
},
[SID_CLANRANKCHANGE] = {
	uint32{label="Cookie", },
	uint8{label="Status", },
},
[SID_PROFILE] = {
	uint32{label="Cookie", },
	uint8{label="Success", },
	stringz{label="Profile\\Description value", },
	stringz{label="Profile\\Location value", },
	uint32{label="Clan Tag", },
},
[SID_GETLADDERDATA] = {
	uint32{label="Ladder type", },
	uint32{label="League", },
	uint32{label="Sort method", },
	uint32{label="Starting rank", },
	uint32{label="Number of ranks listed", },
	uint32{label="Wins", },
	uint32{label="Losses", },
	uint32{label="Disconnects", },
	uint32{label="Rating", },
	uint32{label="Rank", },
	uint32{label="Official wins", },
	uint32{label="Official losses", },
	uint32{label="Official disconnects", },
	uint32{label="Official rating", },
	uint32{label="Unknown", },
	uint32{label="Official rank", },
	uint32{label="Unknown", },
	uint32{label="Unknown", },
	uint32{label="Highest rating", },
	uint32{label="Unknown", },
	uint32{label="Season", },
	wintime{label="Last game time", },
	wintime{label="Official last game time", },
	stringz{label="Name", },
},
[SID_CREATEACCOUNT2] = {
	uint32{label="Status", },
	stringz{label="Account name suggestion", },
},
[SID_FRIENDSREMOVE] = {
	uint8{label="Entry Number", },
},
[D2GS_LOGONRESPONSE] = {
	uint32{label="Unknown - Possible acceptance/request ID", },
},
[SID_GETADVLISTEX] = {
	uint32{label="Number of games", },
	uint32{label="Status", },
	uint16{label="Game Type", },
	uint16{label="Parameter", },
	uint32{label="Language ID", },
	uint16{label="Address Family", },
	uint16{label="Port", },
	uint32{label="Host's IP", },
	uint32{label="sin_zero", },
	uint32{label="sin_zero", },
	uint32{label="Game Status", },
	uint32{label="Elapsed time", },
	stringz{label="Game name", },
	stringz{label="Game password", },
	stringz{label="Game statstring", },
},
[D2GS_SMALLGOLDPICKUP] = {
	uint8{label="Amount", },
},
[SID_CHECKAD] = {
	uint32{label="Ad ID", },
	uint32{label="File extension", },
	wintime{label="Local file time", },
	stringz{label="Filename", },
	stringz{label="Link URL", },
},
[D2GS_COMPSTARTGAME] = {
},
[SID_QUERYREALMS2] = {
	uint32{label="Unknown", },
	uint32{label="Count", },
	uint32{label="Unknown", },
	stringz{label="Realm title", },
	stringz{label="Realm description", },
},
[SID_CLANFINDCANDIDATES] = {
	uint32{label="Cookie", },
	uint8{label="Status", },
	uint8{label="Number of potential candidates", },
	stringz{label="[] Usernames", },
},
[SID_CLANINVITEMULTIPLE] = {
	uint32{label="Cookie", },
	uint8{label="Result", },
	stringz{label="[] Failed account names", },
},
[SID_LOGONCHALLENGEEX] = {
	uint32{label="UDP Token", },
	uint32{label="Server Token", },
},
[SID_QUERYADURL] = {
	uint32{label="Ad ID", },
	stringz{label="Ad URL", },
},
[SID_WARCRAFTGENERAL] = {
	uint8{label="Subcommand ID", },
	uint32{label="Cookie", },
	uint32{label="Icon ID", },
	uint8{label="Number of ladder records to read; this will be between 0", },
	uint32{label="Ladder type; valid types are 'SOLO', 'TEAM', or", },
	uint16{label="Number of wins", },
	uint16{label="Number of losses", },
	uint8{label="Level", },
	uint8{label="Hours until XP decay, if applicable*", },
	uint16{label="Experience", },
	uint32{label="Rank", },
	uint8{label="Number of race records to read; this will be 5 for WAR3", },
	uint16{label="Wins", },
	uint16{label="Losses", },
	uint8{label="Number of team records to read.", },
	uint32{label="Type of team; valid types are '2VS2', '3VS3', and", },
	uint16{label="Number of wins", },
	uint16{label="Number of losses", },
	uint8{label="Level", },
	uint8{label="Hours until XP decay, if applicable*", },
	uint16{label="Experience", },
	uint32{label="Rank", },
	wintime{label="Time of last game played", },
	uint8{label="Number of partners", },
	stringz{label="[] Names of partners", },
	uint32{label="Cookie", },
	uint8{label="Number of ladder records to read; this will be between 0", },
	uint32{label="Ladder type; valid types are 'SOLO', 'TEAM', or", },
	uint16{label="Number of wins", },
	uint16{label="Number of losses", },
	uint8{label="Level", },
	uint8{label="Hours until XP decay, if applicable*", },
	uint16{label="Experience", },
	uint32{label="Rank", },
	uint8{label="Number of race records to read; this will be 5 for WAR3", },
	uint16{label="Wins", },
	uint16{label="Losses", },
	uint32{label="Cookie", },
	uint32{label="Unknown", },
	uint8{label="Tiers", },
	uint8{label="Count", },
	uint32{label="Icon", },
	uint32{label="Name", },
	uint8{label="Race", },
	uint16{label="Wins required", },
	uint8{label="Unknown", },
},
[SID_CLANMEMBERREMOVED] = {
	stringz{label="Clan member name", },
},
[D2GS_SETDWORDATTR] = {
	uint8{label="Attribute - D2GS_SETWORDATTR", },
	uint32{label="Amount", },
},
[SID_CLANMAKECHIEFTAIN] = {
	uint32{label="Cookie", },
	uint8{label="Status", },
},
[SID_CLANQUITNOTIFY] = {
	uint8{label="Status", },
},
[SID_CHATEVENT] = {
	uint32{label="Event ID", },
	uint32{label="User's Flags", },
	uint32{label="Ping", },
	uint32{label="IP Address", },
	uint32{label="Account number", },
	uint32{label="Registration Authority", },
	stringz{label="Username", },
	stringz{label="Text", },
},
[MCP_CREATEQUEUE] = {
	uint32{label="Position", },
},
[PACKET_STATSUPDATE] = {
	uint32{label="Result", },
},
[SID_AUTH_ACCOUNTUPGRADE] = {
	uint32{label="Status", },
	uint32{label="Server Token", },
},
[PACKET_IDLE] = {
},
[SID_LOGONRESPONSE] = {
	uint32{label="Result", },
},
[SID_CHECKDATAFILE2] = {
	uint32{label="Result", },
},
[SID_CLANMOTD] = {
	uint32{label="Cookie", },
	uint32{label="Unknown", },
	stringz{label="MOTD", },
},
[SID_QUERYREALMS] = {
	uint32{label="Unknown", },
	uint32{label="Count", },
	uint32{label="Unknown", },
	stringz{label="Realm title", },
	stringz{label="Realm description", },
},
[MCP_MOTD] = {
	uint8{label="Unknown", },
	stringz{label="MOTD", },
},
[BNLS_LOGONCHALLENGE] = {
	uint32{label="[8] Data for SID_AUTH_ACCOUNTLOGON", },
},
[SID_AUTH_ACCOUNTLOGONPROOF] = {
	uint32{label="Status", },
	uint8{label="[20] Server Password Proof", },
	stringz{label="Additional information", },
},
[SID_STARTVERSIONING2] = {
	wintime{label="MPQ Filetime", },
	stringz{label="MPQ Filename", },
	stringz{label="ValueString", },
},
[MCP_CHARLOGON] = {
	uint32{label="Result", },
},
[MCP_CHARUPGRADE] = {
	uint32{label="Result", },
},
[SID_CLIENTID] = {
	uint32{label="Registration Version", },
	uint32{label="Registration Authority", },
	uint32{label="Account Number", },
	uint32{label="Registration Token", },
},
[SID_MESSAGEBOX] = {
	uint32{label="Style", },
	stringz{label="Text", },
	stringz{label="Caption", },
},
[BNLS_UPGRADECHALLENGE] = {
	uint32{label="Success code.", desc=Descs.YesNo},
},
[BNLS_LOGONPROOF] = {
	uint32{label="[5] Data for SID_AUTH_ACCOUNTLOGONPROOF", },
},
[MCP_CREATEGAME] = {
	uint16{label="Request Id", },
	uint16{label="Game token", },
	uint16{label="Unknown", },
	uint32{label="Result", },
},
[MCP_REQUESTLADDERDATA] = {
	uint8{label="Ladder type", },
	uint16{label="Total response size", },
	uint16{label="Current message size", },
	uint16{label="Total size of unreceived messages", },
	uint16{label="Rank of first entry", },
	uint16{label="Unknown", },
	uint32{label="Number of entries", },
	uint32{label="Unknown", },
	uint64{label="Character experience", },
	uint8{label="Character Flags", },
	uint8{label="Character title", },
	uint16{label="Character level", },
	uint8{label="[16] Character name", },
},
[BNLS_RESERVESERVERSLOTS] = {
	uint32{label="Number of slots reserved", },
},
[BNLS_CDKEY_EX] = {
	uint32{label="Cookie.", },
	uint8{label="Number of CD-keys requested.", },
	uint8{label="Number of", },
	uint32{label="Bit mask .For each successful", },
	uint32{label="Client session key.", },
	uint32{label="CD-key data.", num=9},
},
[SID_GETCHANNELLIST] = {
	stringz{label="[] Channel names, each terminated by a null string.", },
},
[PACKET_ACCOUNT] = {
	uint32{label="Command", },
	uint32{label="Result", },
},
[MCP_GAMELIST] = {
	uint16{label="Request Id", },
	uint32{label="Index", },
	uint8{label="Number of players in game", },
	uint32{label="Status", },
	stringz{label="Game name", },
	stringz{label="Game description", },
},
[BNLS_VERSIONCHECKEX] = {
	uint32{label="Success*", desc=Descs.YesNo},
	uint32{label="Version.", },
	uint32{label="Checksum.", },
	stringz{label="Version check", },
	uint32{label="Cookie.", },
	uint32{label="The latest version code for this", },
},
[SID_NULL] = {
},
[MCP_STARTUP] = {
	uint32{label="Result", },
},
[SID_CLANREMOVEMEMBER] = {
	uint32{label="Cookie", },
	uint8{label="Status", },
},
[SID_LOGONRESPONSE2] = {
	uint32{label="Result", },
	stringz{label="Reason", },
},
[SID_AUTH_ACCOUNTCHANGEPROOF] = {
	uint32{label="Status code", },
	uint8{label="[20] Server password proof for old password", },
},
[BNLS_HASHDATA] = {
	uint32{label="The data hash.Optional:", num=5},
	uint32{label="Cookie. Same as the cookie", },
},
[SID_FRIENDSUPDATE] = {
	uint8{label="Entry number", },
	uint8{label="Friend Location", },
	uint8{label="Friend Status", },
	uint32{label="ProductID", },
	stringz{label="Location", },
},
[PACKET_BOTNETVERSION] = {
	uint32{label="Server Version", },
},
[SID_REGISTRY] = {
	uint32{label="Cookie", },
	uint32{label="HKEY", },
	stringz{label="Registry path", },
	stringz{label="Registry key", },
},
[SID_FINDLADDERUSER] = {
	uint32{label="Rank. Zero-based. 0xFFFFFFFF == Not ranked.", },
},
[SID_CLANMEMBERRANKCHANGE] = {
	uint8{label="Old rank", },
	uint8{label="New rank", },
	stringz{label="Clan member who changed your rank", },
},
[BNLS_AUTHORIZE] = {
	uint32{label="Server code.", },
},
[SID_CHECKDATAFILE] = {
	uint32{label="Status", },
},
[SID_CLANDISBAND] = {
	uint32{label="Cookie", },
	uint8{label="Result", },
},
[BNLS_SERVERLOGONCHALLENGE] = {
	uint32{label="Slot index.", },
	uint32{label="Data for server's SID_AUTH_ACCOUNTLOGON", num=16},
},
[SID_AUTH_ACCOUNTCHANGE] = {
	uint32{label="Status", },
	uint8{label="[32] Salt", },
	uint8{label="[32] Server key", },
},
[MCP_CHARDELETE] = {
	uint32{label="Result", },
},
[SID_REPORTVERSION] = {
	uint32{label="Result", },
	stringz{label="Patch path", },
},
[SID_WARDEN] = {
	bytes{label="Encrypted Packet", },
	uint8{label="Packet Code", },
	uint32{label="[4] MD5 Hash of the current Module", },
	uint32{label="[4] Decryption key for Module", },
	uint32{label="Length of Module", },
	uint16{label="Length of data", },
	bytes{label="Data", },
	uint8{label="String Length", },
	bytes{label="String Data", },
	uint8{label="Check ID", },
	uint8{label="String Index", },
	uint32{label="Address", },
	uint8{label="Length to Read", },
	uint32{label="Unknown", },
	uint32{label="[5] SHA1", },
	uint32{label="Address", },
	uint8{label="Length to Read", },
	uint8{label="IDXor", },
	uint16{label="Length of data", },
	uint32{label="Checksum of data", },
	uint8{label="Unknown", },
	uint8{label="Unknown", },
	uint8{label="Unknown", },
	stringz{label="Library Name", },
	uint32{label="Funct1", },
	uint32{label="Funct2", },
	uint32{label="Funct3", },
	uint32{label="Funct4", },
	uint32{label="[5] Unknown", },
},
[SID_TOURNAMENT] = {
	uint8{label="Unknown", },
	uint8{label="Unknown, maybe number of non-null strings sent?", },
	stringz{label="Description", },
	stringz{label="Unknown", },
	stringz{label="Website", },
	uint32{label="Unknown", },
	stringz{label="Name", },
	stringz{label="Unknown", },
	stringz{label="Unknown", },
	stringz{label="Unknown", },
	uint32{label="Unknown", num=5},
},
[D2GS_UNIQUEEVENTS] = {
	uint8{label="EventId // see below,", },
},
}
